### ISSUE TITLE
Fallback icons missing?

### ISSUE THREAD

**Issue by jone** [4teamwork/ftw.simplelayout#300]
Looks like we've lost the fallback-icons for when we have no `ftw.theming`:
![bildschirmfoto 2016-02-02 um 18 00 58](https://cloud.githubusercontent.com/assets/7469/12757143/fd2f5c62-c9d6-11e5-8d70-08a6bc35a27c.png)

**Comment by bierik** [comment]
@jone Do we still need this fallback icons? The simplelayout is not working without any theme anyway.

**Comment by jone** [comment]
Since `ftw.simplelayout` has no dependency to `ftw.theming` nor to a theme I can expect that it works properly with vanilla Plone. With the current dependency it is a bug that it does not work with vanilla Plone.

We can decide that simplelayout always requires `ftw.theming` by adding it to the list of dependencies though, but this is a strategic decision. Do we want to be bound to theming?
@maethu What is your opinion about that?

**Comment by maethu** [comment]
IMHO it's ok for US to have dependency to ftw.theming. 
This means less to check if we change something, less compatibility issues and we don't need to invest time to make it work again with vanilla plone.

Further: AFAIK the community is not using this package, so it's up to us to define this dep.

BTW: The package works fine with ftw.theming + ftw.simplelayout even if the installed theme is not ftw.theming based.

**Comment by jone** [comment]
So we can just add `ftw.theming` to the dependencies and it can be used easily with vanilla Plone? That would be great! Lets do that!

**Comment by bierik** [comment]
@jone `ftw.simplelayout` with `ftw.theming`installed looks as follows:
![bildschirmfoto 2016-07-01 um 12 21 41](https://cloud.githubusercontent.com/assets/1637820/16519057/b8fa73f8-3f86-11e6-94bd-f2734b2b9a66.png)

The problem here is that the sunburst theme produces CSS like this:
```CSS
#content li {
  margin-bottom: 0.25em;
  line-height: 1.5em;
  display: list-item;
}
```

It should be possible to make it working with the sunburst theme but in my opinion it is not worth it because the most of the project are running the plonetheme.blueberry. To support the onegov theme for zg.ch additional changes are required anyway.
So if we want to make it working this means we want to support the sunburst theme. So how much time should we spend here.

**Comment by bierik** [comment]
Wir warten hier noch auf das Update von `izug` bis wir eine einfachere Situation haben um das abzuschätzen.
