### ISSUE TITLE
Gallery block images open too large in Plone5

### ISSUE THREAD

**Issue by djowett-ftw** [4teamwork/ftw.simplelayout#603]
It seems that some colorbox settings are not set (or not applied) in Plone 5 (note izug seems not to have this issue).  This is not a problem in Plone4.

exhibit a  - HTML
`<div id="colorbox" class="" role="dialog" tabindex="-1" style="display: block; visibility: visible; top: 0px; left: 0px; position: absolute; width: 2930px; height: 2210px;">`

screenshots:
![Screenshot 2020-04-24 at 10 37 05](https://user-images.githubusercontent.com/54800639/80192687-de4a4300-8617-11ea-86fb-9211e9f9c859.png)

Note the lack of right border on the expanded image ( I need a high res screen :-) )

![Screenshot 2020-04-24 at 10 37 23](https://user-images.githubusercontent.com/54800639/80192704-e4402400-8617-11ea-9799-0c23552f7b99.png)

**Comment by djowett-ftw** [comment]
This seems to be caused by https://github.com/4teamwork/ftw.simplelayout/commit/63788820fdcd276574af07753987cc16974077d4 - I can't see why this commit chose to scale ALL images up to 4k resolution.  This means that even small images get scaled up and become blurry. 

Any ideas?

cc @maethu @mbaechtold @Nachtalb @BlueSky9443

**Comment by mbaechtold** [comment]
I have no idea why the author of the pull request https://github.com/4teamwork/ftw.simplelayout/pull/472 chose to introduce and use the 4K image scale. I'm quite sad that the commit message does not contain the reason for the new image scale.

**Comment by djowett-ftw** [comment]
So... Nick thought that the scale was got to stop caching of images and the maximum image size (4k) was used to guarantee the image was at least as big as the original.

I think he should have used the `@@images` view described [here](https://docs.plone.org/develop/plone/images/content.html#using-direct-urls) - but maybe that's the equivalent of what was there already ?

**Comment by Nachtalb** [comment]
@maethu please correct me if I am wrong with anything. This is how I interpret the changes that were made and why they were made like this. 

**Reason for that scale:** With that scale, he fixed a caching issue. As he said in the commit, the problem was that when the image was changed in the gallery it didn't reload the full resolution image because the URL of the image was still the same. By using a scale you get a unique URL for each image. New URL == Browser fetches that new URL instead of using the image it had in the cache. 

**Reason for using `direction='up'`:** The scale has two directions: 
- `down` if the image is larger than your scale it will be scaled down if it is smaller nothing happens 
- `up` if the image is larger than your scale nothing happens if it is smaller it will be scaled up

Now, the goal for the image there is to get the full resolution of the uploaded image. If he uses `up` an image that is larger than his scale will not be scaled in any way and will remain as it is, thus serving the full resolution. If it is smaller, however - and this is where the problem lies - the image was scaled up to his 4k scale. 

**Why does it work in plone4 and not plone5:** https://github.com/4teamwork/ftw.colorbox/blob/2e0f54308d3e8ce19ff120d48efeb30e82a90e38/ftw/colorbox/interfaces.py#L24-L33
The colorbox settings tell it that the image should not get bigger than 100%. In plone 5 this settings is added via pattern settings but I have seen that locally on my machine the pattern settings are missing from the body attributes which is a bit of a mystery to me atm. And the reason why ftw.colorbox does not respect the max size of the image (screen width/height) 

https://github.com/4teamwork/ftw.colorbox/blob/b81557f0022d3ddb380a5e7704a14da34c0719da/ftw/colorbox/browser/initalize_colorbox.py

That means that in plone 5 colorbox doesn't see these options and does not care about how big the image will be. 

**Solution:** I see 2 problems here that have to be solved. 
- The pattern settings defined in ftw.colorbox are not rendered (nor are any other pattern settings for that matter). Why is this happening? Is this a problem due to something in ftw.simplelayout or somewhere else?
- The solution in ftw.simplelayour for solving the caching seems wrong to me. It's a workaround, not a solution. I believe if we did the caching properly we wouldn't need any scale. Also, we want the full resolution image there so not an upscaled image. 
	- we could either change the caching solution 
	- or if we stick with this solution use a scale of 1x1 pixels. This will ensure we still have a unique URL but also that images are not upscaled (keeping `direction='up'`). 

The problem with ftw.simplelayout image caching can be postponed IMHO but the problem with the ftw.colorbox settings not appearing in the body attributes has to be fixed.

**Comment by djowett-ftw** [comment]
@Nachtalb I see colorbox settings in https://devizug.zg.ch/web/behoerden/staatskanzlei/amt-fuer-ungenanntes?sl-state-counter=7

`data-ftw-colorbox-options='{"photo": true,"current": "{current}/{total}","maxWidth": "100%","maxHeight": "100%"}'`

Is that what you were concerned at not seeing?

**Comment by maethu** [comment]
This has been solved in colorbox.

**Comment by djowett-ftw** [comment]
> This has been solved in colorbox.

@maethu Can you point to where?

**Comment by maethu** [comment]
@djowett-ftw You solved it with https://github.com/4teamwork/ftw.colorbox/commit/d9f78cc0a6debc5694d42332c40f2b6aca10b6fc

See https://www.zg.ch/behoerden/gesundheitsdirektion/amt-fur-sport/sportfoerderung/fotogallerie/tenerolager for an example
